# Site
name: "Alvarohf"
title: "Alvarohf"
description: "A page about me, my projects, interests and posts."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
google_analytics: 'UA-46278016-1'
disqus: 'alvarohf'
mailchimp-list: 'https://chimpstatic.com/mcjs-connected/js/users/7208fccdae9bc64cd10d3fcaf/8bb3afeaddc112b8578aaa59e.js'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  alvarohf:
    name: Álvaro
    display_name: Alvarohf
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: alvarodelasherasfer@gmail.com
    web: https://alvarohf.github.io
    twitter: https://twitter.com/Alvarohf_dev
    description: "Computer Engineer who loves coding, tech, news, science and farming."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
